import type { Bike, Booking, Conversation, Owner, User, UserRole } from './types'
import { atDay, dayKey } from '@/lib/format'

export const RENTER = {
  id: 'u-aarav',
  name: 'Aarav Mehta',
  initials: 'AM',
  city: 'Mumbai',
  memberSince: '2021',
  rating: 4.8,
}

export const OWNER_RHEA = {
  id: 'o-rhea',
  name: 'Rhea Kapoor',
  initials: 'RK',
  verified: true,
  responseTime: '~15 min',
  rating: 4.9,
  reviews: 212,
  memberSince: '2019',
  phone: '+91 98220 44120',
  tagline: 'Beach-season bikes, always fuelled and serviced.',
  hue: 38,
} satisfies Owner

export const OWNER_VIKRAM = {
  id: 'o-vikram',
  name: 'Vikram Shetty',
  initials: 'VS',
  verified: true,
  responseTime: '~30 min',
  rating: 4.7,
  reviews: 98,
  memberSince: '2020',
  phone: '+91 98450 11230',
  tagline: 'Performance machines, maintained by a racer.',
  hue: 190,
} satisfies Owner

export const OWNER_ANANYA = {
  id: 'o-ananya',
  name: 'Ananya Fernandes',
  initials: 'AF',
  verified: true,
  responseTime: '~1 hr',
  rating: 4.8,
  reviews: 64,
  memberSince: '2021',
  phone: '+91 94220 77810',
  tagline: 'Vintage beauties with stories to tell.',
  hue: 330,
} satisfies Owner

export const OWNER_SAMEER = {
  id: 'o-sameer',
  name: 'Sameer Naik',
  initials: 'SN',
  verified: true,
  responseTime: '~45 min',
  rating: 4.6,
  reviews: 41,
  memberSince: '2022',
  phone: '+91 98900 33455',
  tagline: 'Fleet host · 15+ bikes across North Goa.',
  hue: 120,
} satisfies Owner

export const seedOwners: Owner[] = [OWNER_RHEA, OWNER_VIKRAM, OWNER_ANANYA, OWNER_SAMEER]

/** Demo login credentials — kept in one place so auth UI and seed data stay in sync. */
export const DEMO_RENTER_EMAIL = `${RENTER.id.replace('u-', '')}@ridegoa.in`
export const DEMO_HOST_EMAIL = `${OWNER_RHEA.id.replace('o-', '')}@ridegoa.in`

/** Demo login password shared by all seeded accounts. */
export const DEMO_PASSWORDS: Record<string, string> = {
  'u-aarav': 'demo1234',
  'o-rhea': 'demo1234',
  'o-vikram': 'demo1234',
  'o-ananya': 'demo1234',
  'o-sameer': 'demo1234',
}

/** Accounts directory — renter + every host is a signable demo account. */
export const seedUsers: User[] = [
  {
    id: RENTER.id,
    name: RENTER.name,
    initials: RENTER.initials,
    email: DEMO_RENTER_EMAIL,
    hue: 38,
    verified: true,
    roles: ['renter'],
    passwordHash: '',
    memberSince: '2021',
    city: 'Mumbai',
    rating: 4.8,
  },
  ...seedOwners.map((o) => ({
    id: o.id,
    name: o.name,
    initials: o.initials,
    email: `${o.id.replace('o-', '')}@ridegoa.in`,
    hue: o.hue,
    verified: o.verified,
    roles: ['owner'] as UserRole[],
    passwordHash: '',
    memberSince: o.memberSince,
    responseTime: o.responseTime,
    rating: o.rating,
    reviews: o.reviews,
    phone: o.phone,
    tagline: o.tagline,
  })),
]

export const seedBikes: Bike[] = [
  {
    id: 'b-anjuna-activa',
    name: 'Anjuna Sunset Scooty',
    category: 'scooter',
    brand: 'Honda',
    model: 'Activa 125',
    year: 2023,
    cc: 125,
    transmission: 'Automatic',
    mileage: '52 km/l',
    ratePerDay: 399,
    ratePerHour: 65,
    securityDeposit: 2000,
    helmetIncluded: true,
    gearIncluded: true,
    location: 'Anjuna',
    mapPos: { x: 32, y: 12 },
    distanceKm: 1.2,
    rating: 4.8,
    reviews: 187,
    ownerId: OWNER_RHEA.id,
    description:
      'The go-to beach hopper for Anjuna. Under-seat storage for two helmets, USB charging, and a matte-sand finish that hides the beach dust. Easy to park at Curlies and the flea market.',
    rentalRules: [
      'Valid two-wheeler licence required',
      'Return with the same fuel level',
      'No riding on beaches or off-road',
      'Late return charged per hour',
    ],
    features: ['Helmets x2', 'Phone mount', 'USB charging', 'Under-seat storage', 'Rain poncho'],
    blockedDates: [],
    available: true,
    tripsCompleted: 340,
    listedAt: atDay(-90),
    tone: 0,
    photo: '/bikes/anjuna-sunset-scooty.svg',
    photoUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/a/a5/Honda_Activa_Rental-_Goa_6.jpg/1280px-Honda_Activa_Rental-_Goa_6.jpg',
  },
  {
    id: 'b-baga-classic',
    name: 'Baga Beach Classic 350',
    category: 'cruiser',
    brand: 'Royal Enfield',
    model: 'Classic 350',
    year: 2022,
    cc: 349,
    transmission: 'Manual',
    mileage: '35 km/l',
    ratePerDay: 649,
    ratePerHour: 110,
    securityDeposit: 3000,
    helmetIncluded: true,
    gearIncluded: false,
    location: 'Baga',
    mapPos: { x: 30, y: 20 },
    distanceKm: 2.8,
    rating: 4.9,
    reviews: 254,
    ownerId: OWNER_RHEA.id,
    description:
      'The iconic thumper, tuned for lazy beach runs and sunset rides along Baga–Calangute. Jawan brown with chrome accents, twin exhaust note you will hear for a week.',
    rentalRules: [
      'Gear-shift bike — manual riders only',
      'Valid licence + security deposit on card',
      'Fuel: return as received',
      'Free helmet + riding gloves included',
    ],
    features: ['Chrome mirrors', 'Touring seat', 'Toolkit', 'Riding gloves'],
    blockedDates: [],
    available: true,
    tripsCompleted: 412,
    listedAt: atDay(-120),
    tone: 1,
    photo: '/bikes/baga-classic-350.svg',
    photoUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/2/26/Royal_Enfield_Classic_350_2010_Model.jpg/1280px-Royal_Enfield_Classic_350_2010_Model.jpg',
  },
  {
    id: 'b-candolim-rc390',
    name: 'Candolim Rocket 390',
    category: 'sports',
    brand: 'KTM',
    model: 'RC 390',
    year: 2024,
    cc: 373,
    transmission: 'Manual',
    mileage: '26 km/l',
    ratePerDay: 899,
    ratePerHour: 150,
    securityDeposit: 5000,
    helmetIncluded: true,
    gearIncluded: true,
    location: 'Candolim',
    mapPos: { x: 34, y: 28 },
    distanceKm: 4.1,
    rating: 4.7,
    reviews: 96,
    ownerId: OWNER_VIKRAM.id,
    description:
      'Track-bred corner-carver for riders who want the ghats to themselves. Quickshifter, slipper clutch, and a bark that turns heads from Candolim to Chorla Ghat.',
    rentalRules: [
      'Minimum 2 years riding experience',
      'Full riding gear provided & mandatory',
      'Deposit refunded on return inspection',
      'No pillion during the first hour',
    ],
    features: ['Full riding gear', 'Quickshifter', 'Phone mount', 'Tyre pressure kit'],
    blockedDates: [dayKey(atDay(3)), dayKey(atDay(4))],
    available: true,
    tripsCompleted: 87,
    listedAt: atDay(-45),
    tone: 2,
    photo: '/bikes/candolim-rc390.svg',
    photoUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/4/41/KTM_RC390_Photo-1449426468159-d96dbf08f19f_2015.jpg/1280px-KTM_RC390_Photo-1449426468159-d96dbf08f19f_2015.jpg',
  },
  {
    id: 'b-vagator-himalayan',
    name: 'Vagator Adventure 450',
    category: 'adventure',
    brand: 'Royal Enfield',
    model: 'Himalayan 450',
    year: 2024,
    cc: 452,
    transmission: 'Manual',
    mileage: '30 km/l',
    ratePerDay: 799,
    ratePerHour: 135,
    securityDeposit: 4000,
    helmetIncluded: true,
    gearIncluded: true,
    location: 'Vagator',
    mapPos: { x: 38, y: 6 },
    distanceKm: 3.4,
    rating: 4.8,
    reviews: 143,
    ownerId: OWNER_RHEA.id,
    description:
      'Built for the red laterite trails and jungle roads of interior Goa. Tall suspension, crash guards, and a luggage rack — the full ADV touring setup, highway-ready.',
    rentalRules: [
      'Off-road capable, beach sand still off-limits',
      'Panniers available on request',
      'Fuel policy: full-to-full',
      'Valid licence mandatory',
    ],
    features: ['Crash guards', 'Luggage rack', 'Tall windscreen', 'USB + 12V', 'Panniers (on request)'],
    blockedDates: [],
    available: true,
    tripsCompleted: 176,
    listedAt: atDay(-60),
    tone: 3,
    photo: '/bikes/vagator-himalayan-450.svg',
    photoUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/e/e9/Royal_Enfield_Himalayan_450_Mana_Black.jpg/1280px-Royal_Enfield_Himalayan_450_Mana_Black.jpg',
  },
  {
    id: 'b-palolem-bullet',
    name: 'Palolem Vintage Bullet 500',
    category: 'vintage',
    brand: 'Royal Enfield',
    model: 'Bullet 500',
    year: 2013,
    cc: 499,
    transmission: 'Manual',
    mileage: '28 km/l',
    ratePerDay: 549,
    ratePerHour: 95,
    securityDeposit: 3500,
    helmetIncluded: false,
    gearIncluded: false,
    location: 'Palolem',
    mapPos: { x: 40, y: 86 },
    distanceKm: 38,
    rating: 4.6,
    reviews: 58,
    ownerId: OWNER_ANANYA.id,
    description:
      'A 2013 Bullet with hand-painted tank art and a kick-start ritual that feels like time travel. Slow, loud, and impossibly charming down the South Goa coast road.',
    rentalRules: [
      'No highway speeds — enjoy the scenic route',
      'Kick-start demo provided at handover',
      'Helmet BYO (₹150/day rental available)',
      'Service backup on call across South Goa',
    ],
    features: ['Hand-painted tank', 'Solo sprung seat', 'Toolkit pouch', 'Chrome exhaust'],
    blockedDates: [],
    available: true,
    tripsCompleted: 64,
    listedAt: atDay(-30),
    tone: 4,
    photo: '/bikes/palolem-bullet-500.svg',
    photoUrl:
      'https://upload.wikimedia.org/wikipedia/commons/thumb/1/17/Royal_Enfield_Bullet_500_G5.jpg/1280px-Royal_Enfield_Bullet_500_G5.jpg',
  },
  {
    id: 'b-panjim-ather',
    name: 'Panjim Ather 450X',
    category: 'electric',
    brand: 'Ather',
    model: '450X',
    year: 2024,
    cc: 0,
    transmission: 'Automatic',
    mileage: '105 km/charge',
    ratePerDay: 499,
    ratePerHour: 85,
    securityDeposit: 2500,
    helmetIncluded: true,
    gearIncluded: false,
    location: 'Panjim',
    mapPos: { x: 58, y: 42 },
    distanceKm: 9.6,
    rating: 4.8,
    reviews: 121,
    ownerId: OWNER_RHEA.id,
    description:
      'Silent, zippy and ideal for exploring Fontainhas and the Mandovi promenade. 105 km real-world range, fast-charges at the Panjim Ather grid while you have fish curry rice.',
    rentalRules: [
      'Charged to 100% at pickup',
      'Range mode limits top speed to 40 km/h',
      'Return with ≥20% charge',
      'Fast-charge card included',
    ],
    features: ['Fast-charge card', '7" dash with maps', 'Bluetooth speakers', 'Helmet x2'],
    blockedDates: [],
    available: true,
    tripsCompleted: 210,
    listedAt: atDay(-20),
    tone: 5,
    photo: '/bikes/panjim-ather-450x.svg',
    photoUrl:
      'https://images.unsplash.com/photo-1558618666-fcd25c85cd64?auto=format&fit=crop&w=1200&h=800&q=80',
  },
]

export const seedBookings: Booking[] = [
  {
    id: 'bk-1',
    bikeId: 'b-anjuna-activa',
    renterId: RENTER.id,
    ownerId: OWNER_RHEA.id,
    status: 'Pending',
    start: atDay(2),
    end: atDay(5),
    pickupTime: '11:00',
    dropoffTime: '19:00',
    days: 3,
    dailyRate: 399,
    securityDeposit: 2000,
    serviceFee: 96,
    helmetAddon: true,
    helmetCost: 450,
    total: 3743,
    conversationId: 'con-1',
    createdAt: atDay(-1, 18),
  },
  {
    id: 'bk-2',
    bikeId: 'b-baga-classic',
    renterId: RENTER.id,
    ownerId: OWNER_RHEA.id,
    status: 'Active',
    start: atDay(-2),
    end: atDay(3),
    pickupTime: '10:00',
    dropoffTime: '18:00',
    days: 5,
    dailyRate: 649,
    securityDeposit: 3000,
    serviceFee: 260,
    helmetAddon: true,
    helmetCost: 750,
    total: 7255,
    conversationId: 'con-2',
    createdAt: atDay(-7, 12),
    handover: {
      bodyItems: [
        { label: 'No new scratches or dents', checked: true },
        { label: 'Tyres & pressure good', checked: true },
        { label: 'Brakes & clutch working', checked: true },
        { label: 'Lights & indicators OK', checked: true },
        { label: 'Mirrors intact', checked: true },
      ],
      fuelLevel: 100,
      odometer: 12340,
      photo: 'snap-1',
      signature: 'sig-aarav',
      at: atDay(-2, 10),
    },
  },
  {
    id: 'bk-3',
    bikeId: 'b-vagator-himalayan',
    renterId: RENTER.id,
    ownerId: OWNER_RHEA.id,
    status: 'Completed',
    start: atDay(-28),
    end: atDay(-24),
    pickupTime: '09:00',
    dropoffTime: '17:00',
    days: 4,
    dailyRate: 799,
    securityDeposit: 4000,
    serviceFee: 256,
    helmetAddon: false,
    helmetCost: 0,
    total: 7452,
    conversationId: 'con-none',
    createdAt: atDay(-32, 16),
    review: {
      rating: 5,
      comment:
        'Smooth ride through the Western Ghats — the Himalayan ate the laterite roads for breakfast. Handover was 10 minutes flat.',
      at: atDay(-22, 20),
    },
  },
]

export const seedConversations: Conversation[] = [
  {
    id: 'con-1',
    bikeId: 'b-anjuna-activa',
    bookingId: 'bk-1',
    renterId: RENTER.id,
    ownerId: OWNER_RHEA.id,
    unread: { renter: 0, owner: 1 },
    messages: [
      {
        id: 'm-1-1',
        fromRole: 'renter',
        fromId: RENTER.id,
        kind: 'text',
        text: 'Hey! Booking sent for the Activa — 3 days from the 4th. Is pickup at Anjuna beach road okay?',
        timestamp: atDay(-1, 17),
        read: true,
        readByOther: true,
      },
      {
        id: 'm-1-2',
        fromRole: 'owner',
        fromId: OWNER_RHEA.id,
        kind: 'text',
        text: 'Got it, Aarav! I usually meet at the St. Michael’s church corner, 100m from your stay. Two helmets + rain poncho will be in the boot. I’ll confirm the booking in a bit 👍',
        timestamp: atDay(-1, 17, 30),
        read: true,
        readByOther: true,
      },
    ],
  },
  {
    id: 'con-2',
    bikeId: 'b-baga-classic',
    bookingId: 'bk-2',
    renterId: RENTER.id,
    ownerId: OWNER_RHEA.id,
    unread: { renter: 2, owner: 0 },
    messages: [
      {
        id: 'm-2-1',
        fromRole: 'system',
        fromId: 'system',
        kind: 'system',
        text: 'Booking #bk-2 was approved. Rental starts at Baga · 10:00.',
        timestamp: atDay(-5, 11),
        read: true,
        readByOther: true,
      },
      {
        id: 'm-2-2',
        fromRole: 'renter',
        fromId: RENTER.id,
        kind: 'text',
        text: 'We’re parked at Britto’s side road, in a white Scorpio.',
        timestamp: atDay(-2, 9, 40),
        read: true,
        readByOther: true,
      },
      {
        id: 'm-2-3',
        fromRole: 'owner',
        fromId: OWNER_RHEA.id,
        kind: 'text',
        text: 'Checklist done — tank full, 12,340 km on the odo. The Classic is fuelled and gloved up. Ride safe! 🏍️',
        timestamp: atDay(-2, 10),
        read: true,
        readByOther: true,
      },
      {
        id: 'm-2-4',
        fromRole: 'renter',
        fromId: RENTER.id,
        kind: 'text',
        text: 'Thank you Rhea! The Classic handles the Baga potholes beautifully 😄 If the sunset view at the fort is anything to go by, best decision ever.',
        timestamp: atDay(-1, 19, 12),
        read: false,
        readByOther: false,
      },
      {
        id: 'm-2-5',
        fromRole: 'owner',
        fromId: OWNER_RHEA.id,
        kind: 'location',
        text: 'Shared a pin for the drop-off point',
        timestamp: atDay(0, 9, 5),
        read: false,
        readByOther: false,
        location: { label: 'Rhea’s Garage · Baga Beach Road', x: 46, y: 58 },
      },
    ],
  },
  {
    id: 'con-3',
    bikeId: 'b-candolim-rc390',
    renterId: RENTER.id,
    ownerId: OWNER_VIKRAM.id,
    unread: { renter: 1, owner: 0 },
    messages: [
      {
        id: 'm-3-1',
        fromRole: 'renter',
        fromId: RENTER.id,
        kind: 'text',
        text: 'Hi Vikram — is the RC 390 free next weekend? Want it for a Chorla Ghat sunrise run.',
        timestamp: atDay(0, 8, 10),
        read: true,
        readByOther: true,
      },
      {
        id: 'm-3-2',
        fromRole: 'owner',
        fromId: OWNER_VIKRAM.id,
        kind: 'text',
        text: 'Yes! Saturday pickup works. Helmet + full gear included. Bring your licence and riding gloves — I’ll have the quickshifter fuelled and ready.',
        timestamp: atDay(0, 8, 40),
        read: false,
        readByOther: false,
      },
    ],
  },
]
